create table USUARIO (
   USU_CODIGO integer NOT NULL,
   USU_NOME VARCHAR(60) NOT NULL,
   USU_DT_NASCIMENTO date, 
   USU_DT_CADASTRO timestamp,
   USU_EMAIL VARCHAR(60),
   USU_TELEFONE VARCHAR(14),
   CONSTRAINT PK_USUARIO PRIMARY KEY (USU_CODIGO)
);

create generator SEQ_USUARIO;